;; Marketing Compliance Verifier
(define-constant contract-owner tx-sender)
(define-constant err-not-found (err u101))
(define-constant err-unauthorized (err u102))
(define-constant err-invalid-status (err u103))
(define-constant status-pending u1)
(define-constant status-approved u2)
(define-constant status-rejected u3)
(define-constant claim-unverified u1)
(define-constant claim-verified u2)
(define-data-var material-id-nonce uint u0)
(define-data-var claim-id-nonce uint u0)
(define-data-var total-materials uint u0)
(define-data-var total-violations uint u0)
(define-map marketing-materials { material-id: uint } { company: principal, title: (string-ascii 100), content-hash: (string-ascii 64), material-type: (string-ascii 50), status: uint, submitted-at: uint, reviewed-at: uint })
(define-map claims { claim-id: uint } { material-id: uint, claim-text: (string-ascii 200), evidence-hash: (string-ascii 64), status: uint, verified: bool })
(define-map compliance-reviews { material-id: uint } { reviewer: principal, compliant: bool, notes: (string-ascii 200), reviewed-at: uint })
(define-map violations { material-id: uint } { violation-type: (string-ascii 100), severity: uint, reported-at: uint })
(define-map company-materials { company: principal, index: uint } { material-id: uint })
(define-map company-material-count { company: principal } { count: uint })
(define-private (get-next-material-id) (let ((current-id (var-get material-id-nonce))) (var-set material-id-nonce (+ current-id u1)) current-id))
(define-private (get-next-claim-id) (let ((current-id (var-get claim-id-nonce))) (var-set claim-id-nonce (+ current-id u1)) current-id))
(define-public (submit-material (title (string-ascii 100)) (content-hash (string-ascii 64)) (material-type (string-ascii 50))) (let ((material-id (get-next-material-id)) (company-count (default-to { count: u0 } (map-get? company-material-count { company: tx-sender })))) (map-set marketing-materials { material-id: material-id } { company: tx-sender, title: title, content-hash: content-hash, material-type: material-type, status: status-pending, submitted-at: stacks-block-height, reviewed-at: u0 }) (map-set company-materials { company: tx-sender, index: (get count company-count) } { material-id: material-id }) (map-set company-material-count { company: tx-sender } { count: (+ (get count company-count) u1) }) (var-set total-materials (+ (var-get total-materials) u1)) (ok material-id)))
(define-public (add-claim (material-id uint) (claim-text (string-ascii 200)) (evidence-hash (string-ascii 64))) (let ((claim-id (get-next-claim-id)) (material (unwrap! (map-get? marketing-materials { material-id: material-id }) err-not-found))) (asserts! (is-eq tx-sender (get company material)) err-unauthorized) (map-set claims { claim-id: claim-id } { material-id: material-id, claim-text: claim-text, evidence-hash: evidence-hash, status: claim-unverified, verified: false }) (ok claim-id)))
(define-public (review-material (material-id uint) (compliant bool) (notes (string-ascii 200))) (let ((material (unwrap! (map-get? marketing-materials { material-id: material-id }) err-not-found))) (map-set compliance-reviews { material-id: material-id } { reviewer: tx-sender, compliant: compliant, notes: notes, reviewed-at: stacks-block-height }) (map-set marketing-materials { material-id: material-id } (merge material { status: (if compliant status-approved status-rejected), reviewed-at: stacks-block-height })) (ok true)))
(define-public (report-violation (material-id uint) (violation-type (string-ascii 100)) (severity uint)) (let ((material (unwrap! (map-get? marketing-materials { material-id: material-id }) err-not-found))) (map-set violations { material-id: material-id } { violation-type: violation-type, severity: severity, reported-at: stacks-block-height }) (var-set total-violations (+ (var-get total-violations) u1)) (ok true)))
(define-public (verify-claim (claim-id uint)) (let ((claim (unwrap! (map-get? claims { claim-id: claim-id }) err-not-found))) (map-set claims { claim-id: claim-id } (merge claim { status: claim-verified, verified: true })) (ok true)))
(define-read-only (get-material (material-id uint)) (map-get? marketing-materials { material-id: material-id }))
(define-read-only (get-claim (claim-id uint)) (map-get? claims { claim-id: claim-id }))
(define-read-only (get-review (material-id uint)) (map-get? compliance-reviews { material-id: material-id }))
(define-read-only (get-violation (material-id uint)) (map-get? violations { material-id: material-id }))
(define-read-only (get-company-material (company principal) (index uint)) (map-get? company-materials { company: company, index: index }))
(define-read-only (get-platform-stats) { total-materials: (var-get total-materials), total-violations: (var-get total-violations) })
